### ISSUE TITLE
Error when eating apple

### ISSUE THREAD

**Issue by ghost** [qbcore-redm-framework/qbr-smallresources#14]
When I went to eat an apple I got stuck in an endless eating loop and the error "No such export Progressbar in resource qbr-core" popped up in my client console 
![Screenshot 2022-04-04 195525](https://user-images.githubusercontent.com/64894726/161652420-f63cea67-3f14-4f05-9f00-742080d74a8d.png)

**Comment by vanadis1** [comment]
Update qbr-core please.

**Comment by vanadis1** [comment]
@Molicheu And close issue pls.
